[package]
name = "text-editor"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "text-editor"
path = "src/main.rs"

[dependencies]
crossterm = "0.28.1"
tempfile = "3.15.0"
env_logger = "0.11.6"
log = "0.4.25"
